name: build-and-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          docker build -t bloggingdemo:latest .
          docker run bloggingdemo:latest dotnet test
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        run: |
          echo ::set-env name=IMAGE_TAG::${GITHUB_REF#refs/heads/}-$(echo $GITHUB_RUN_NUMBER)
          docker tag bloggingdemo:latest ${{ secrets.DOCKERHUB_USERNAME }}/bloggingdemo:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bloggingdemo:${{ env.IMAGE_TAG }}
